apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nextcloud-memory
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nextcloud-test # deployment name
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 40
