apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nextcloud
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1v1beta1
    kind: Deployment
    name: nextcloud-test # name of deployment
  targetCPUUtilizationPercentage: 30 # cpu sues 30 $ then automatically autoscale
